### ISSUE TITLE
LoadError: cannot load such file -- selly/statistics

### ISSUE THREAD

**Issue by davidpatters0n** [SellyGG/selly-ruby#1]
When requiring the gem in IRB it tries to load `selly/statistics` which does not exists  - https://github.com/Selly/selly-ruby/tree/master/lib/selly. Maybe this file accidentally wasn't committed 🙃

**Comment by Sexual** [comment]
@davidpatters0n This should now be fixed in `2.0.2`.

**Comment by davidpatters0n** [comment]
Awesome thanks.
